// <auto-generated />
using System;
using AiContextBrain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiContextBrain.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526130000_AddLemonSqueezyToUser")]
    partial class AddLemonSqueezyToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.4.25258.110")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiContextBrain.Models.AIContext", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("Content").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ProjectId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("AIContexts");
                });

            modelBuilder.Entity("AiContextBrain.Models.ArchitectureRule", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("FolderPath").HasColumnType("text");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Pattern").IsRequired().HasColumnType("text");
                    b.Property<string>("ProjectId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("ArchitectureRules");
                });

            modelBuilder.Entity("AiContextBrain.Models.CodingConvention", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Example").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Language").HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("ProjectId").IsRequired().HasColumnType("text");
                    b.Property<string>("Rule").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("CodingConventions");
                });

            modelBuilder.Entity("AiContextBrain.Models.ExtensionAuth", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Token").IsRequired().HasColumnType("text");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Token").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("ExtensionAuths");
                });

            modelBuilder.Entity("AiContextBrain.Models.FrameworkPattern", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("CommonDependencies").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DetectionRules").IsRequired().HasColumnType("jsonb");
                    b.Property<string>("FolderStructure").IsRequired().HasColumnType("jsonb");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("TypicalCommands").HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("FrameworkPatterns");
                });

            modelBuilder.Entity("AiContextBrain.Models.Project", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("ArchitectureType").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("AuthSystem").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DatabaseType").HasColumnType("text");
                    b.Property<string>("Framework").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Path").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("UserId").HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "Path", "UserId" }).IsUnique().HasDatabaseName("IX_Projects_Path_UserId");
                    b.HasIndex("UserId");
                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AiContextBrain.Models.ProjectScan", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("ArchitectureType").HasColumnType("text");
                    b.Property<int>("FilesCount").HasColumnType("integer");
                    b.Property<string>("FolderStructureJson").IsRequired().HasColumnType("jsonb").HasDefaultValue("[]");
                    b.Property<string>("Framework").HasColumnType("text");
                    b.Property<int>("LinesOfCode").HasColumnType("integer");
                    b.Property<string>("ProjectId").IsRequired().HasColumnType("text");
                    b.Property<string>("ScanData").IsRequired().HasColumnType("jsonb");
                    b.Property<DateTime>("ScanDate").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("ProjectScans");
                });

            modelBuilder.Entity("AiContextBrain.Models.SystemDecision", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("Category").HasColumnType("text");
                    b.Property<string>("Decision").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("DecisionDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("ProjectId").IsRequired().HasColumnType("text");
                    b.Property<string>("Reasoning").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("SystemDecisions");
                });

            modelBuilder.Entity("AiContextBrain.Models.User", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("ApiToken").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<DateTime?>("LastLoginAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("LsCurrentPeriodEnd").HasColumnType("text");
                    b.Property<string>("LsCustomerId").HasColumnType("text");
                    b.Property<string>("LsSubscriptionId").HasColumnType("text");
                    b.Property<string>("LsSubscriptionStatus").HasColumnType("text");
                    b.Property<string>("LsVariantId").HasColumnType("text");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                    b.Property<int>("Plan").HasColumnType("integer").HasDefaultValue(0);
                    b.Property<int>("ScanCount").HasColumnType("integer").HasDefaultValue(0);
                    b.Property<DateTime>("ScanResetDate").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("AiContextBrain.Models.AIContext", b =>
                {
                    b.HasOne("AiContextBrain.Models.Project", "Project").WithMany("AIContexts").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AiContextBrain.Models.ArchitectureRule", b =>
                {
                    b.HasOne("AiContextBrain.Models.Project", "Project").WithMany("ArchitectureRules").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AiContextBrain.Models.CodingConvention", b =>
                {
                    b.HasOne("AiContextBrain.Models.Project", "Project").WithMany("CodingConventions").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AiContextBrain.Models.ExtensionAuth", b =>
                {
                    b.HasOne("AiContextBrain.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("AiContextBrain.Models.Project", b =>
                {
                    b.HasOne("AiContextBrain.Models.User", "User").WithMany().HasForeignKey("UserId");
                    b.Navigation("User");
                });

            modelBuilder.Entity("AiContextBrain.Models.ProjectScan", b =>
                {
                    b.HasOne("AiContextBrain.Models.Project", "Project").WithMany("Scans").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AiContextBrain.Models.SystemDecision", b =>
                {
                    b.HasOne("AiContextBrain.Models.Project", "Project").WithMany("SystemDecisions").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AiContextBrain.Models.Project", b =>
                {
                    b.Navigation("AIContexts");
                    b.Navigation("ArchitectureRules");
                    b.Navigation("CodingConventions");
                    b.Navigation("Scans");
                    b.Navigation("SystemDecisions");
                });
#pragma warning restore 612, 618
        }
    }
}
